# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version: 0.1

default:
  global:
    parameters:
      region: ap-southeast-2
      stack_name: poc-hello-sam-kai
  build:
    parameters:
      cached: true
      parallel: true
      # build_in_source: true
      debug: true
  validate:
    parameters:
      lint: true
  deploy:
    parameters:
      s3_prefix: poc-hello-sam-kai
      capabilities: CAPABILITY_IAM
      resolve_s3: true
      on_failure: ROLLBACK
      confirm_changeset: true
