AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  hello-sam
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Architectures:
      - x86_64
    CodeUri: src/lambda
    Timeout: 30
    Tracing: Active
    MemorySize: 192
    Runtime: nodejs18.x
    # You can add LoggingConfig parameters such as the Log format, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Stage:
    Type: String
    Default: dev
    MinLength: '3'
    MaxLength: '3'
    Description: Stage name

# More info about Metadata: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
Metadata:
  EsbuildConfig:
    BuildMethod: esbuild
    BuildProperties:
      Minify: false
      Target: es2022
      Sourcemap: true
      SourcesContent: false

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: hello.lambdaHandler
      FunctionName: !Sub ${AWS::StackName}-${Stage}-hello
      Events:
        Hello:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      <<:
        BuildMethod: esbuild
        BuildProperties:
          Minify: false
          Target: es2022
          Sourcemap: true
          SourcesContent: false

  SamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sam.handler
      FunctionName: !Sub ${AWS::StackName}-${Stage}-sam
      Events:
        Sam:
          Type: Api
          Properties:
            Path: /sam
            Method: get
    Metadata:
      <<:
        BuildMethod: esbuild
        BuildProperties:
          Minify: false
          Target: es2022
          Sourcemap: true
          SourcesContent: false

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-${Stage}-StateMachine
      Type: STANDARD
      Tracing:
        Enabled: true
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      Policies:
        - AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: '*'
        - LambdaInvokePolicy:
            FunctionName: !Ref HelloFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SamFunction
      DefinitionSubstitutions:
        HelloFunction: !Ref HelloFunction
        SamFunction: !Ref SamFunction
      DefinitionUri: state-machines/state-machine.asl.yml

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/vendedlogs/states/${AWS::StackName}-${ResourceId}-Logs
        - ResourceId: StateMachine

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloApi:
  #   Description: API Gateway endpoint URL for Hello function
  #   Value: !Sub
  #     - https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/hello/
  #     - Stage: !Ref StageName
  HelloFunction:
    Description: Hello Lambda Function ARN
    Value: !GetAtt HelloFunction.Arn
  HelloFunctionIamRole:
    Description: Implicit IAM Role created for Hello function
    Value: !GetAtt HelloFunctionRole.Arn